### ISSUE TITLE
Alerts for event is not showing

### ISSUE THREAD

**Issue by tiongghee** [ibm-watson-iot/iota-starter-server-fm#4]
Hi,

I tried creating events on the path of my vehicle but the alerts for the events are not displayed. I am able to get the alerts for overheating or low fuel but not alerts for events.

Please advise if I am missing any configuration.

Thank you.

**Comment by ibmmarudai** [comment]
Hi,

The IoT for Automotive service seemed not to be working this weekend. Could you try to re-create a new service instance? I checked alerts for events today.

**Comment by tiongghee** [comment]
@ibmmarudai I tried to redeploy but the problem persisted. It seem like there was a major activity in Bluemix on Monday; Now I am not even able to start my Fleet Management application.
